# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# создание БД для тестов
services:
  - postgresql
before_install:
  - psql -c "CREATE DATABASE url_shortcut;" -U postgres

env:
  global:
    - CODECOV_TOKEN="1b156e08-9bdd-458b-8f2f-a76c9b75525a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - selesitomorozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always